[build]
  command = "npm run build" # Or your preferred build command for your frontend
  publish = "dist" # Or your preferred publish directory for your frontend

[functions]
  directory = "netlify/functions" # This is the default, but explicitly setting it is good practice